### ISSUE TITLE
Revise ABM skimming procedure

### ISSUE THREAD

**Issue by bettinardi** [RSGInc/SOABM#17]
Currently my understanding is that the ABM is configured to use "profile" speeds for skimming for all iterations.  On 6-14-17's call we identified that in the final release of the ABM (after calibration) only the first iteration should be doing a "warm start" with profile speeds.  After that it should switch to coded free flow speeds.  Additionally, for future scenarios we won't want to maintain period specific profile speeds for each link, so another option will need to be built in, where instead of using profile speeds from the network, or free flow, there will be a lookup table of profile speeds by a series of settings (dimensions; time-of-time, speed, FC, lanes...), and the code will need to use that look-up table for skimming speeds for the first iteration, and then the standard speed field with assignment for all following... 

Please ask @jfdman or @bettinardi with any questions.

**Comment by bstabler** [comment]
This is done:

"Currently my understanding is that the ABM is configured to use "profile" speeds for skimming for all iterations. On 6-14-17's call we identified that in the final release of the ABM (after calibration) only the first iteration should be doing a "warm start" with profile speeds. After that it should switch to coded free flow speeds. "

This still needs to be completed:

"Additionally, for future scenarios we won't want to maintain period specific profile speeds for each link, so another option will need to be built in, where instead of using profile speeds from the network, or free flow, there will be a lookup table of profile speeds by a series of settings (dimensions; time-of-time, speed, FC, lanes...), and the code will need to use that look-up table for skimming speeds for the first iteration, and then the standard speed field with assignment for all following..."

**Comment by bstabler** [comment]
opened #20 and closed this issue
